sudo: required
dist: trusty
language: python
cache: pip3
python:
  - "3.6"
# command to install dependencies
install:
  - sudo apt-get -y install python3-pip
  - pip3 install -r requirements.txt
  - cd tests
script: 
  - pytest
notifications:
    slack: dedsec-inside:24NHg47gypeVR3DWnEncRq7c
